# Generated by Django 5.2 on 2025-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_doctor_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
