# Generated by Django 5.2 on 2025-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
