# Generated by Django 5.2 on 2025-11-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_doctor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
    ]
