# Generated by Django 5.2 on 2025-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, default='hello', max_length=255, null=True),
        ),
    ]
