# Generated by Django 5.2 on 2025-11-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_doctor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
    ]
