# Generated by Django 5.2 on 2025-11-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_remove_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
